import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'One-on-One Mentoring Sessions',
    rating: 4.5,
    ratingCount: 9,
    price: '8 - 12',
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Career Guidance Sessions',
    rating: 5,
    ratingCount: 15,
    price: '8 - 12',
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Code Debugging Sessions',
    rating: 4,
    ratingCount: 7,
    price: '10 - 15',
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Software Development Sessions',
    rating: 4,
    ratingCount: 12,
    price: '10 - 15',
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'Software Planning Sessions',
    rating: 4,
    ratingCount: 32,
    price: '15 - 20',
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Group Mentoring Sessions',
    rating: 4,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  // {
  //   id: 7,
  //   cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
  //   title: 'Adobe Light Room For Beginners: Complete Photo Editing',
  //   rating: 4,
  //   ratingCount: 6,
  //   price: 25,
  //   category: 'Beginner',
  // },
]
